name: sol
dependencies:
  - python=3.7
  - pip=20.0
  - pip:
    - numpy
    - pandas
    - rdkit
    - torch
    - tqdm
    - typing-extensions
    - typed-argument-parser
    - tensorboardX
    - scikit-learn
    - hyperopt
    - requests
    - FPSim2