name: eos
channels:
  # - pytorch
  # - efelix
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip=20.0
  - pip:
    - numpy
    - pandas==1.5.3
    - rdkit
    - torch==1.6.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
    - torch
    - FPSim2
    - tqdm
    - typing-extensions
    - typed-argument-parser
    - tensorboardX
    - scikit-learn
    - hyperopt
    - requests