name: eos74bo
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip=20.0
  - pip:
    - numpy
    - pandas
    - rdkit
    - torch
    - FPSim2
    - tqdm
    - typing-extensions
    - typed-argument-parser
    - tensorboardX
    - scikit-learn
    - hyperopt
    - requests